apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
type: Opaque
data:
  username: {{ .Values.secrets.mysqlUser | b64enc | quote }}
  password: {{ .Values.secrets.mysqlPassword | b64enc | quote }}


