# Default values for mysql-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: latest
  pullPolicy: IfNotPresent

volume:
  name: mysql-data
  size: 10Gi

service:
  name: mysql
  type: ClusterIP
  port: 3306

secrets:
  mysqlUser: myuser
  mysqlPassword: mypassword

